/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionhotel.frame;

import gestionhotel.dto.Habitacion;
import gestionhotel.dto.Reserva;
import gestionhotel.service.HabitacionService;
import gestionhotel.service.ReservaService;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CrearReserva extends javax.swing.JFrame {

    private ReservaService reservaService;
    private GestionReservas gestionReservas;
    private HabitacionService habitacionService;
    private Integer idReserva;
    private boolean isEdit = false;

    /**
     * Creates new form CrearReserva
     */
    public CrearReserva() {
        initComponents();
        reservaService = new ReservaService();
        habitacionService = new HabitacionService();
        loadHabitacionesLibres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCed = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textNom = new javax.swing.JTextPane();
        comboHab1 = new javax.swing.JComboBox<>();
        chekcActivo = new javax.swing.JCheckBox();
        fechaInicioDater = new com.toedter.calendar.JDateChooser();
        fechaFinDater = new com.toedter.calendar.JDateChooser();
        btnCrear = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Crear reserva");

        jLabel2.setText("Cedula Cliente");

        jLabel3.setText("Nombre Cliente");

        jLabel4.setText("Habitacion");

        jLabel5.setText("Fecha Inicio");

        jLabel6.setText("Fecha Fin");

        jLabel7.setText("Activo");
        jLabel7.setToolTipText("");

        jScrollPane1.setViewportView(textCed);

        jScrollPane2.setViewportView(textNom);

        comboHab1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar opción" }));

        chekcActivo.setText("Activo");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chekcActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1)
                                            .addComponent(jScrollPane2)
                                            .addComponent(comboHab1, 0, 247, Short.MAX_VALUE)
                                            .addComponent(fechaInicioDater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fechaFinDater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cancelarBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboHab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(fechaInicioDater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fechaFinDater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chekcActivo))
                .addGap(18, 18, 18)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String cedula = this.textCed.getText();
        String nombre = this.textNom.getText();
        String habitacion = (String) this.comboHab1.getSelectedItem();
        Date fechaInicio = this.fechaInicioDater.getDate();
        Date fechaFin = this.fechaFinDater.getDate();
        boolean activo = this.chekcActivo.isSelected();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(null, "La cedula del cliente es obligatoria");
            return;
        }

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre del cliente es obligatorio");
            return;
        }

        if (habitacion.equals("Seleccionar opción")) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una habitacion");
            return;
        }

        if (fechaInicio == null) {
            JOptionPane.showMessageDialog(null, "Fecha inicio es obligatorio");
            return;
        }

        if (fechaFin == null) {
            JOptionPane.showMessageDialog(null, "Fecha fin es obligatorio");
            return;
        }

        Reserva reserva = new Reserva();
        reserva.setCedulaCliente(cedula);
        reserva.setNombreCliente(nombre);
        reserva.setIdHabitacion(habitacion);
        reserva.setFechaInicio(fechaInicio);
        reserva.setFechaFin(fechaFin);
        reserva.setActivo(activo);
        if (isEdit) {
            reserva.setId(idReserva);
            reservaService.editReserva(reserva);
            this.gestionReservas.loadData();
            JOptionPane.showMessageDialog(null, "Reserva editada correctamente");
        } else {
            reservaService.crearReserva(reserva);
            this.gestionReservas.loadData();
            JOptionPane.showMessageDialog(null, "Reserva creada correctamente");
        }
        dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    public void setReservaData(boolean isEdit, Reserva reserva, GestionReservas gestionReservas) {
        this.gestionReservas = gestionReservas;
        this.isEdit = isEdit;
        if (isEdit) {
            this.idReserva = reserva.getId();
            this.textCed.setText(reserva.getCedulaCliente());
            this.textNom.setText(reserva.getNombreCliente());
            this.comboHab1.addItem(reserva.getIdHabitacion());
            this.comboHab1.setSelectedItem(reserva.getIdHabitacion());
            this.comboHab1.disable();
            this.fechaInicioDater.setDate(reserva.getFechaInicio());
            this.fechaFinDater.setDate(reserva.getFechaFin());
            this.chekcActivo.setSelected(reserva.isActivo());
            this.jLabel1.setText("Editar reserva");
            this.btnCrear.setText("Editar");

        }

    }

    public void loadHabitacionesLibres() {
        List<Habitacion> habitacionesLibres = habitacionService.getHabitacionesLibres();
        habitacionesLibres.forEach(hab -> {
            this.comboHab1.addItem((hab.getCodigo()));
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JCheckBox chekcActivo;
    private javax.swing.JComboBox<String> comboHab1;
    private com.toedter.calendar.JDateChooser fechaFinDater;
    private com.toedter.calendar.JDateChooser fechaInicioDater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane textCed;
    private javax.swing.JTextPane textNom;
    // End of variables declaration//GEN-END:variables
}
